### PR TITLE
Update EquipmentManagement.cs

### LINKED ISSUE #8: case 4 doesn't work in DisplayMenu()
## PR #5 ## 

**How to reproduce** 
1. Choose EquipmentManagement menu using number key "2"
2. Press number key "4" to exit EquipmentManagement menu.

### PR DESCRIPTION
**Pull request by CCianfloneDev**
Added ability for user to add/remove cages from system in menu.

### CODE REVIEW

**Review by DZ-FSDev — CHANGES_REQUESTED** [review]
**Change Requests for EquipmentManagement.cs**
- [x] The field `zooName` should be changed to `zoo` as it references the Zoo the equipment belongs
- [x] Make sure documentation for parameters and summaries are full sentences.
- [x] Another way to avoid the `goto` is to move the default behavior common to all cases outside the switch inside `DisplayMenu()`
- [x] The same can be applied to common behavior in other cases in `DisplayMenu()`
- [x] Most console menus are designed with `Console.Clear()` calls at the start of render, or end of render. Try to ensure this is consistent in `DisplayMenu()`

**Review by DZ-FSDev — COMMENTED** [review]
I'll take a look today. Pull PR #5 5c3563ffb6331b57940a9df94169bcd4ad89f88c

**Comment by DZ-FSDev** [comment]
Made changes to address Issue #8

**Review by CCianfloneDev — COMMENTED** [review]
Awesome, thanks.

**Review by CCianfloneDev — COMMENTED** [review]
Beautiful, going to test this now.

**Review by DZ-FSDev — APPROVED** [review]
Changes look good!

**Pull request merged**
