### PR TITLE
Adding files for ZooKeepingSystem

### PR DESCRIPTION
**Pull request by CCianfloneDev**
Requesting DZ-FSDev to review.

### CODE REVIEW

**Review by DZ-FSDev — COMMENTED** [review]
Consider project WIP. May require a large collection of enumerations to represent the Genus and Species of animals.
hqdefault

**Review by DZ-FSDev — CHANGES_REQUESTED** [review]
**Change Requests for Program.cs**
- [x] Try getting the elements of the Species enum as an array and using LINQ Cast to receive an Iterable<Species> (see https://stackoverflow.com/questions/1167361/how-do-i-convert-an-enum-to-a-list-in-c)
- [x] Consider using an infinite loop with sentinel value to allow continuous interaction until the user is done

**Change Requests for Species.cs**
- [x] Periods on documentation lines 24 & 29

**Change Requests for Zoo.cs**
- [x] Expand on param documentation line 17
- [x] Missing return documentation line 28
- [x] ToString() should not return with a line break at the end of the representation.

**Comment by CCianfloneDev** [comment]
I've added an EmployeeManagement.cs, EquipmentManagement.cs, and AnimalManagement.cs. The idea is to make the program work like a "mock" zoo keeping system that employees can access to change the zoo's data.

**Review by DZ-FSDev — APPROVED** [review]
Looks good. Let's merge changes and start atomic PRs.

**Pull request merged**
